import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import {
  MatIconModule,
  MatListModule,
  MatCardModule,
  MatSortModule,
  MatMenuModule,
  MatTreeModule,
  MatTabsModule,
  MatBadgeModule,
  MatInputModule,
  MatRadioModule,
  MatTableModule,
  MatButtonModule,
  MatSelectModule,
  MatDialogModule,
  MatToolbarModule,
  MatSidenavModule,
  MatStepperModule,
  MatGridListModule,
  MatFormFieldModule,
  MatPaginatorModule,
  MatProgressBarModule,
  MatProgressSpinnerModule,
  MatChipsModule
} from '@angular/material';
import { FlexLayoutModule } from '@angular/flex-layout';

@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    MatIconModule,
    MatListModule,
    MatCardModule,
    MatSortModule,
    MatMenuModule,
    MatTreeModule,
    MatTabsModule,
    MatBadgeModule,
    MatInputModule,
    MatRadioModule,
    MatTableModule,
    MatChipsModule,
    MatButtonModule,
    MatSelectModule,
    MatDialogModule,
    MatToolbarModule,
    FlexLayoutModule,
    MatSidenavModule,
    MatStepperModule,
    MatGridListModule,
    MatFormFieldModule,
    MatPaginatorModule,
    MatProgressBarModule,
    MatProgressSpinnerModule
  ],
  exports: [
    CommonModule,
    MatIconModule,
    MatListModule,
    MatCardModule,
    MatSortModule,
    MatMenuModule,
    MatTreeModule,
    MatTabsModule,
    MatBadgeModule,
    MatInputModule,
    MatRadioModule,
    MatTableModule,
    MatChipsModule,
    MatButtonModule,
    MatSelectModule,
    MatDialogModule,
    MatToolbarModule,
    FlexLayoutModule,
    MatSidenavModule,
    MatStepperModule,
    MatGridListModule,
    MatFormFieldModule,
    MatPaginatorModule,
    MatProgressBarModule,
    MatProgressSpinnerModule
  ]
})
export class MaterialModule { }
